---
- name: copy k3s service file
  template:
    src: k3s-agent.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0755

- name: start and enable k3s service
  systemd:
    name: k3s.service
    daemon_reload: yes
    state: started
    enabled: yes
