---
# Doc: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: let iptables see bridged traffic
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  loop:
  - net.ipv6.conf.all.forwarding
  - net.bridge.bridge-nf-call-ip6tables
  - net.ipv4.ip_forward
  - net.bridge.bridge-nf-call-iptables

- name: download k3s binary arm64
  get_url:
    url: 'https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/{{ k3s_binary_download }}'
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
