---
- import_tasks: common.yml

# Setup server machine
- import_tasks: server.yml
  when: k3s_cluster_role == 'server'

# Setup agent machine(s)
- import_tasks: agent.yml
  when: k3s_cluster_role == 'agent'
